name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        CRYPTO_SECRET: ${{ secrets.CRYPTO_SECRET }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        WX_APPID: ${{ secrets.WX_APPID }}
        WX_SECRET: ${{ secrets.WX_SECRET }}
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
        OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /root/wonderland-backend

          git pull origin main
          
          # 创建新的.env文件
          cat > .env << EOF
          DATABASE_URL="${DATABASE_URL}"
          JWT_SECRET="${JWT_SECRET}"
          CRYPTO_SECRET="${CRYPTO_SECRET}"
          MAIL_HOST="${MAIL_HOST}"
          MAIL_PORT="${MAIL_PORT}"
          MAIL_USER="${MAIL_USER}"
          MAIL_PASS="${MAIL_PASS}"
          WX_APPID="${WX_APPID}"
          WX_SECRET="${WX_SECRET}"
          OSS_ACCESS_KEY_ID="${OSS_ACCESS_KEY_ID}"
          OSS_ACCESS_KEY_SECRET="${OSS_ACCESS_KEY_SECRET}"
          OSS_BUCKET="${OSS_BUCKET}"
          OSS_ENDPOINT="${OSS_ENDPOINT}"
          EOF
          
          # 安装依赖并构建
          pnpm install
          pnpm build
          
          # 使用PM2重启服务
          pm2 restart wonderland-backend || pm2 start dist/main.js --name wonderland-backend